# Generated by Django 2.2.7 on 2020-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anons',
            field=models.CharField(max_length=254, verbose_name='Краткая информация о новости.'),
        ),
    ]
