# Generated by Django 2.2.7 on 2020-10-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datatime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
